--- #YAML:1.0
name:                Class-Declare
version:             0.10
abstract:            Declare classes with public, private and protected
license:             ~
author:              
    - Ian Brayshaw <ian@onemore.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Storable:                      0
    Test::Exception:               0.15
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
